### ISSUE TITLE
 wgpu-hal heuristics assumed that the view dimension will be equal to `Cube` rather than `CubeArray`

### ISSUE THREAD

**Issue by orhun** [cxreiff/lifecycler#1]
Hello!

I'm getting a bunch of these errors spammed in my terminal when I try to run `lifecycler` (latest version):

```
2024-07-31T11:46:09.178073Z ERROR wgpu_hal::gles: wgpu-hal heuristics assumed that the view dimension will be equal to `Cube` rather than `CubeArray`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`
```

any ideas? 🐟

**Comment by cxreiff** [comment]
I got those as well on my linux partition- looking into it.

**Comment by cxreiff** [comment]
Appears to be a relatively recent bevy-wide issue: https://github.com/bevyengine/bevy/issues/13115

As it doesn't appear to affect the rendering other than displacing it, I'll work on suppressing the error as a quick fix.

**Comment by cxreiff** [comment]
Removed error logging for now, should work now (fixed in repo and crates.io, github/itch.io releases postponed until past the jam judging period). Thanks for the report!

**Comment by orhun** [comment]
Yeah, I tried with `RUST_LOG=none` and it worked fine. Thanks for the fix! Are you planning to create a new release soon?

btw I created an AUR package here: <https://aur.archlinux.org/packages/lifecycler>  I'm happy to add installation instructions to the repo :)

**Comment by cxreiff** [comment]
I'll disable itch.io upload and trigger a release (jam judging still going on).

And thank you! Yes if you wouldn't mind, I'll merge it.
